version: '3'

services:
  db:
    image: mysql:5.7.22
    restart: always
    environment: 
      MYSQL_DATABASE: finapp
      MYSQL_USER: finapp
      MYSQL_PASSWORD: finapp
      MYSQL_ROOT_PASSWORD: finapp
    env_file: 
      - .env
    volumes: 
      - .dbdata:/var/lib/mysql
    ports:
      - 33068:3306
  redis:
    image: "redis:alpine"
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A finapp worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A finapp beat -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

volumes:
  dbdata:
