version: '3.3'
services: 
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8000:8000
    volumes: 
      - .:/app
    depends_on: 
      - db
      - redis
  redis:
    image: "redis:alpine"
  
    
  celery:
    build: .
    command: celery -A finapp worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A finapp beat
    volumes:
      - .:/app
    depends_on:
      - db
      - redis


  
  db:
    image: mysql:5.7.22
    restart: always
    environment: 
      MYSQL_DATABASE: finapp
      MYSQL_USER: finapp
      MYSQL_PASSWORD: finapp
      MYSQL_ROOT_PASSWORD: finapp
    env_file: 
      - .env
    volumes: 
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306
