# Generated by Django 3.0.6 on 2020-05-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('opening_date', models.CharField(max_length=255)),
                ('parentid', models.IntegerField()),
            ],
            options={
                'db_table': 'office',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'role',
            },
        ),
    ]
