# Generated by Django 3.1.4 on 2021-03-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0002_auto_20210328_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='openOn',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
