# Generated by Django 3.0.6 on 2020-05-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0002_office_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresstable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('addressLine', models.TextField()),
                ('street', models.CharField(max_length=255)),
                ('landmark', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('mnemonic', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'addresstable',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerId', models.CharField(max_length=255)),
                ('officeId', models.IntegerField()),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('mnemonic', models.CharField(max_length=100)),
                ('activationDate', models.CharField(max_length=255)),
                ('submittedDate', models.CharField(max_length=255)),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='IdentificationId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('modeOfId', models.CharField(max_length=255)),
                ('idNo', models.CharField(max_length=255)),
                ('mnemonic', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'identification_id',
            },
        ),
    ]
