# Generated by Django 3.0.6 on 2020-05-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0004_auto_20200521_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
