# Generated by Django 3.1.4 on 2021-04-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0005_user_is_head_teller'),
    ]

    operations = [
        migrations.AddField(
            model_name='teller',
            name='is_head_teller',
            field=models.BooleanField(default=False),
        ),
    ]
