# Generated by Django 3.0.6 on 2020-05-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0005_auto_20200521_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresstable',
            name='mobileNo',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='activationDate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
