# Generated by Django 3.1.4 on 2021-04-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0006_teller_is_head_teller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='loanStatus',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_paid',
            field=models.BooleanField(default=False),
        ),
    ]
