# Generated by Django 3.0.6 on 2020-05-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0006_auto_20200521_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerId', models.CharField(max_length=255)),
                ('mnemonic', models.CharField(max_length=255)),
                ('accounNumber', models.CharField(max_length=255)),
                ('ledgerBalance', models.FloatField()),
                ('workingBalance', models.FloatField()),
                ('accountTypeId', models.IntegerField()),
                ('accountType', models.CharField(max_length=255)),
                ('active', models.BooleanField()),
                ('createdBy', models.CharField(max_length=255)),
                ('openOn', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('accountId', models.IntegerField()),
            ],
            options={
                'db_table': 'accountCategory',
            },
        ),
    ]
