# Generated by Django 3.1.4 on 2021-04-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0007_auto_20210419_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_code', models.TextField(blank=True, null=True)),
                ('loan_name', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'loan_type',
            },
        ),
    ]
