# Generated by Django 3.0.6 on 2020-05-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0007_account_accountcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accountName',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
