# Generated by Django 3.1.4 on 2021-04-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0008_loantype'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantype',
            name='loan_duration',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
