# Generated by Django 3.0.6 on 2020-05-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0008_account_accountname'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transId', models.CharField(max_length=255)),
                ('transDate', models.CharField(max_length=255)),
                ('transAmount', models.FloatField()),
                ('senderName', models.CharField(max_length=255)),
                ('senderAccount', models.CharField(max_length=255)),
                ('receiverName', models.CharField(max_length=255)),
                ('receiverAccount', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'transaction_history',
            },
        ),
        migrations.RenameField(
            model_name='account',
            old_name='ledgerBalance',
            new_name='previousBalance',
        ),
    ]
