# Generated by Django 3.0.6 on 2020-05-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0009_auto_20200524_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('tellerId', models.CharField(max_length=100)),
                ('tellerName', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'teller',
            },
        ),
        migrations.CreateModel(
            name='TellerBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('tellerId', models.CharField(max_length=100)),
                ('openDate', models.CharField(max_length=100)),
                ('openBal', models.FloatField()),
                ('closeDate', models.CharField(max_length=100)),
                ('closeBal', models.FloatField()),
                ('totaltran', models.FloatField()),
            ],
            options={
                'db_table': 'teller_balance',
            },
        ),
        migrations.CreateModel(
            name='TellerTransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('tellerId', models.CharField(max_length=100)),
                ('transAmount', models.FloatField()),
                ('transAccount', models.CharField(max_length=100)),
                ('transType', models.CharField(max_length=100)),
                ('transDate', models.CharField(max_length=100)),
                ('tellerName', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'teller_transaction_history',
            },
        ),
    ]
