# Generated by Django 3.1.4 on 2021-04-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0010_auto_20210419_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='duration',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='pay_day',
            field=models.TextField(blank=True, null=True),
        ),
    ]
