# Generated by Django 3.1.4 on 2021-04-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0011_auto_20210419_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='transDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
