# Generated by Django 3.1.4 on 2021-04-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0012_auto_20210419_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='pay_day',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
