# Generated by Django 3.1.4 on 2021-04-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0013_auto_20210419_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='pay_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
