# Generated by Django 3.0.6 on 2020-05-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0013_auto_20200526_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tellerbalance',
            name='bal',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='tellerbalance',
            name='openBal',
            field=models.FloatField(default='0'),
        ),
    ]
