# Generated by Django 3.1.4 on 2021-04-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0014_auto_20210419_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalTransactHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.TextField(blank=True, null=True)),
                ('txn_id', models.TextField(blank=True, null=True)),
                ('frm_acct', models.TextField(blank=True, null=True)),
                ('to_acct', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('product_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'internal_history',
            },
        ),
        migrations.CreateModel(
            name='InternalWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.TextField(blank=True, null=True)),
                ('product_name', models.TextField(blank=True, null=True)),
                ('account_number', models.TextField(blank=True, null=True)),
                ('prev_bal', models.FloatField(default=0)),
                ('working_bal', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'internal_wallet',
            },
        ),
    ]
