# Generated by Django 3.0.6 on 2020-05-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0015_auto_20200528_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='tellerbalance',
            name='status',
            field=models.CharField(default='open', max_length=100),
        ),
    ]
