# Generated by Django 3.1.4 on 2021-04-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0016_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InternalWallet',
            new_name='InternalAccount',
        ),
        migrations.AlterModelTable(
            name='internalaccount',
            table='internal_account',
        ),
    ]
