# Generated by Django 3.0.6 on 2020-05-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0016_tellerbalance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanId', models.CharField(max_length=255)),
                ('customerId', models.CharField(max_length=255)),
                ('accountNumber', models.CharField(max_length=255)),
                ('customerName', models.TextField()),
                ('loanAmount', models.FloatField()),
                ('loanOfficer', models.CharField(max_length=255)),
                ('loanBal', models.FloatField()),
                ('loanStatus', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'loan_appliaction',
            },
        ),
    ]
