# Generated by Django 3.0.6 on 2020-05-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0018_loanapplication_loantype'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='dateApply',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='dateApprove',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
