# Generated by Django 3.1.4 on 2021-04-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0018_internaltransacthistory_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_code', models.CharField(max_length=100)),
                ('cur_name', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'currency',
            },
        ),
    ]
