# Generated by Django 3.0.6 on 2020-06-06 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0019_auto_20200528_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnemonic', models.CharField(max_length=100)),
                ('doc', models.FileField(blank=True, max_length=255, null=True, upload_to='customer/%Y/%M/%D/')),
                ('approve', models.BooleanField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finappservice.Customer')),
            ],
            options={
                'db_table': 'customer_document',
            },
        ),
    ]
