# Generated by Django 3.1.4 on 2021-04-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0019_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantype',
            name='interest',
            field=models.FloatField(null=True),
        ),
    ]
