# Generated by Django 3.0.6 on 2020-06-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0020_customerdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdocument',
            name='customer',
        ),
    ]
