# Generated by Django 3.1.4 on 2021-04-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0020_loantype_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tellerbalance',
            name='status',
        ),
        migrations.AddField(
            model_name='tellerbalance',
            name='bal_open',
            field=models.BooleanField(default=True),
        ),
    ]
