# Generated by Django 3.0.6 on 2020-06-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0021_remove_customerdocument_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerDocument',
        ),
        migrations.AddField(
            model_name='customer',
            name='doc',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='customer/%Y/%M/%D/'),
        ),
    ]
