# Generated by Django 3.1.4 on 2021-04-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0021_auto_20210425_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tellerbalance',
            name='bal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tellerbalance',
            name='closeBal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tellerbalance',
            name='closeDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tellerbalance',
            name='openDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tellerbalance',
            name='totaltran',
            field=models.FloatField(blank=True),
        ),
    ]
