# Generated by Django 3.1.4 on 2021-04-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0022_auto_20210425_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tellerbalance',
            name='totaltran',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
