# Generated by Django 3.0.6 on 2020-06-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0023_auto_20200606_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificationid',
            name='doc',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='customer'),
        ),
    ]
