# Generated by Django 3.1.4 on 2021-04-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0023_auto_20210425_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tellerbalance',
            name='closeDate',
            field=models.DateTimeField(null=True),
        ),
    ]
