# Generated by Django 3.0.6 on 2020-06-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0024_auto_20200606_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identificationid',
            name='doc',
        ),
    ]
