# Generated by Django 3.1.4 on 2021-04-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0024_auto_20210425_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='TellerDayBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teller_id', models.TextField(blank=True, null=True)),
                ('open_date', models.DateTimeField(auto_now=True)),
                ('working_bal', models.FloatField(null=True)),
                ('closing_bal', models.FloatField(null=True)),
                ('close_date', models.DateTimeField(null=True)),
                ('till_open', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'teller_day_business',
            },
        ),
    ]
