# Generated by Django 3.0.6 on 2020-06-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0025_remove_identificationid_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smsName', models.TextField()),
                ('account_sid', models.TextField()),
                ('auth_token', models.TextField()),
            ],
            options={
                'db_table': 'twilio',
            },
        ),
    ]
