# Generated by Django 3.1.4 on 2021-04-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0025_tellerdaybusiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='tellerdaybusiness',
            name='total_trans',
            field=models.FloatField(null=True),
        ),
    ]
