# Generated by Django 3.0.6 on 2020-06-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0026_twilio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twilio',
            name='smsName',
            field=models.TextField(default='twilio'),
        ),
    ]
