# Generated by Django 3.1.4 on 2021-04-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0026_tellerdaybusiness_total_trans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tellerbalance',
            name='closeBal',
        ),
        migrations.RemoveField(
            model_name='tellerbalance',
            name='closeDate',
        ),
        migrations.RemoveField(
            model_name='tellerbalance',
            name='totaltran',
        ),
    ]
