# Generated by Django 3.1.4 on 2021-05-11 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0027_auto_20210425_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tellertransactionhistory',
            name='teller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
