# Generated by Django 3.1.4 on 2021-05-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0028_auto_20210511_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='tellertransactionhistory',
            name='txn_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='txn_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
