# Generated by Django 3.1.4 on 2021-05-11 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finappservice', '0029_auto_20210511_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tellertransactionhistory',
            name='txn_type',
        ),
    ]
